# Generated by Django 5.2.8 on 2026-05-06 14:02

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_product_description_product_short_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='detailed_specifications',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bảng Thông số kỹ thuật (Tab Thông số)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Bài viết giới thiệu (Tab Mô tả chi tiết)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='specifications',
            field=models.TextField(blank=True, null=True, verbose_name='Thông số kỹ thuật (Trang chủ)'),
        ),
    ]
