# Generated by Django 5.2.8 on 2026-05-17 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_userprofile_password_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Danh mục', 'verbose_name_plural': 'Danh mục'},
        ),
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Tin tức', 'verbose_name_plural': 'Tin tức sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Đơn hàng', 'verbose_name_plural': 'Đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Chi tiết đơn hàng', 'verbose_name_plural': 'Chi tiết đơn hàng'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Sản phẩm', 'verbose_name_plural': 'Sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Ảnh phụ sản phẩm', 'verbose_name_plural': 'Ảnh phụ sản phẩm'},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'verbose_name': 'Đánh giá khách hàng', 'verbose_name_plural': 'Đánh giá khách hàng'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Hồ sơ người dùng', 'verbose_name_plural': 'Hồ sơ người dùng'},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'verbose_name': 'Danh sách yêu thích', 'verbose_name_plural': 'Danh sách yêu thích'},
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tên màu (VD: Cam, Xám, Tím)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/colors/', verbose_name='Ảnh thu nhỏ màu này')),
                ('price', models.IntegerField(default=0, verbose_name='Giá bán của màu này')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='home.product')),
            ],
            options={
                'verbose_name': 'Màu sắc sản phẩm',
                'verbose_name_plural': 'Màu sắc sản phẩm',
            },
        ),
    ]
