# Generated by Django 5.2.8 on 2026-06-07 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevenueReport',
            fields=[
            ],
            options={
                'verbose_name': 'Báo cáo doanh thu',
                'verbose_name_plural': 'Báo cáo doanh thu',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('home.order',),
        ),
        migrations.AddField(
            model_name='product',
            name='so_luong',
            field=models.IntegerField(default=50, verbose_name='Số lượng tồn kho'),
        ),
    ]
