# Generated by Django 5.2.8 on 2026-05-12 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
