# Generated by Django 5.2.8 on 2026-05-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Chờ xác nhận'), ('Shipping', 'Đang giao hàng'), ('Completed', 'Hoàn thành (Đã nhận)'), ('Cancelled', 'Đã hủy')], default='Pending', max_length=20),
        ),
    ]
